version: "3"

services:
  postgres-server:
    image: postgres:14.0
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    container_name: postgres-server
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "myuser", "-d", "mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  data-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: data-generator
    command: ["--db-host", "postgres-server", "--dataset", "${DATA:-iris}"]
    depends_on:
      postgres-server:
        condition: service_healthy

networks:
  default:
    name: mlops-network